#!/bin/sh
# Define target rush
if [ $# -eq 0 ] ; then
	echo "No target rush supplied"
	exit
fi
# Destroy /obj/ and any executable
if [ -d obj ] ; then
	./clean
fi
# Recreate /obj/ 
if [ ! -d obj ] ; then
	mkdir obj 2>&1 >/dev/null
fi
target=$(find $1.c | cut -c 1- | sed 's/.\{2\}$//')
gcc -Wall -Wextra -Werror -c $target.c -o obj/$target.o
gcc -Wall -Wextra -Werror -c main.c -o obj/main.o
gcc -Wall -Wextra -Werror -c ft_putchar.c -o obj/ft_putchar.o 
gcc -Wall -Wextra -Werror -o _$target obj/*.o
echo "$target output:"
./_$target